# Generated by Django 2.1.1 on 2019-04-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('url', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('url', models.CharField(max_length=420, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('trackers', models.ManyToManyField(blank=True, null=True, to='api.Tracker')),
            ],
        ),
        migrations.DeleteModel(
            name='URLAssociations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
