# Generated by Django 2.1.1 on 2019-04-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190429_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Website'),
        ),
    ]
