# Generated by Django 2.1.1 on 2019-04-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, to='api.Website'),
        ),
    ]
