# Generated by Django 2.1.1 on 2019-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLAssociations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=420)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
