# Generated by Django 2.1.1 on 2019-04-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlassociations',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlassociations',
            name='url',
            field=models.CharField(max_length=420, primary_key=True, serialize=False),
        ),
    ]
